<a href="https://colab.research.google.com/github/manasesmutembei11/Colab-Notebook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [ ]:
a = np.arange(5)

print(a <= 3)

[ True  True  True  True False]


In [3]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


In [4]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [9]:
output = np.ones((7, 7))

z = np.zeros((5, 5))
z[3, 3] = 5

output[1:-1, 1:-1] = z

In [12]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
print(b)

[ 1  2 20  4  5]


In [13]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
print(b)

15
